//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using FreeSql.DataAnnotations;
using YoShop.Models;

namespace YoShop
{
    [JsonObject(MemberSerialization.OptIn), Table(Name = "spec")]
    public partial class Spec : WxappEntity
    {
        [JsonProperty, Column(Name = "spec_id", DbType = "int(11) unsigned", IsIdentity = true,IsPrimary = true)]
        public uint SpecId { get; set; }

        [JsonProperty, Column(Name = "spec_name")]
        public string SpecName { get; set; }
    }
}
